basePath: /
host: server-validation-cep-mepu6h3qaa-uc.a.run.app
info:
  contact:
    email: luanaands@gmail.com
    name: Luana Andrade
  description: API para consulta do tempo real de um CEP utilizando a API do ViaCEP
    e da WeatherAPI.
  termsOfService: http://swagger.io/terms/
  title: Desafio CEP API - golang
  version: "1.0"
paths:
  /weather:
    get:
      consumes:
      - application/json
      description: Retorna dados do tempo consultando ViaCEP e WeatherAPI
      parameters:
      - description: 'CEP sem formatação (ex: 01001000)'
        in: query
        name: cep
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      summary: Buscar clima atual
      tags:
      - CEP
schemes:
- https
swagger: "2.0"
