basePath: /
host: localhost:8081
info:
  contact:
    email: luanaands@gmail.com
    name: Luana Andrade
  description: API interna para consulta do tempo real de um CEP utilizando a API
    do ViaCEP e da WeatherAPI.
  termsOfService: http://swagger.io/terms/
  title: Desafio CEP API - golang
  version: "1.0"
paths:
  /cep:
    get:
      consumes:
      - application/json
      description: Retorna dados do tempo consultando ViaCEP e WeatherAPI
      parameters:
      - description: 'CEP sem formatação (ex: 01001000)'
        in: query
        name: cep
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      summary: Service B - Buscar localidade e clima atual
      tags:
      - CEP
schemes:
- https
swagger: "2.0"
