basePath: /
definitions:
  dto.CepRequest:
    properties:
      cep:
        type: string
    type: object
host: localhost:8082
info:
  contact:
    email: luanaands@gmail.com
    name: Luana Andrade
  description: API para consulta do tempo real de um CEP
  termsOfService: http://swagger.io/terms/
  title: Desafio CEP API - golang
  version: "1.0"
paths:
  /cep:
    post:
      consumes:
      - application/json
      description: Retorna informações do CEP
      parameters:
      - description: 'CEP sem formatacao (ex: 01001000)'
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.CepRequest'
      produces:
      - application/json
      responses: {}
      summary: Service A - Buscar informações do CEP
      tags:
      - CEP
schemes:
- https
swagger: "2.0"
